#!/bin/bash
if [ $# -ne 4 ]; then
	echo "Usage: $0 <number 1>, <number 2> <number 3> <number 4>"
	exit 1
fi

n1=$1
n2=$2
n3=$3
n4=$4

if ! [[ "$n1" =~ ^-?[0-9]+$ ]] || ! [[ "$n2" =~ ^-?[0-9]+$ ]] || \
	! [[ "$n3" =~ ^-?[0-9]+$ ]] || ! [[ "$n4" =~ ^-?[0-9]+$ ]]; then
	echo "Error: all parametrs must be integers"
	exit 1
fi

echo "Parameter 1: $n1"
echo "Parameter 2: $n2"
echo "Parameter 3: $n3"
echo "Parameter 4: $n4"

max=$n1
if [ "$n2" -gt "$max" ]; then max=$n2; fi
if [ "$n3" -gt "$max" ]; then max=$n3; fi
if [ "$n4" -gt "$max" ]; then max=$n4; fi

echo "Maximum: $max"




